services:
  webui:
    image: 172.22.23.162:5000/node:18
    container_name: pku_media_service
    restart: always
    ports:
      - "8082:8082"
    user: 1000:1000
    network_mode: host
    volumes:
      - .\dist:/dist/
      # 全景视频数据
      - .\media_data\video:/dist/video/
      # 高斯数据
      - .\media_data\gs_data:/dist/gaussianSplat/gs_data/
    working_dir: /dist
    command: npm run start
    # command: bash
    # tty: true